### ISSUE TITLE
Revoked Access Token - No longer can set new access token up

### ISSUE THREAD

**Issue by maxinetakeba** [nextcloud/integration_gitlab#100]
Per the title

I set a access token and during my troubleshooting I revoked it (as it wouldn't connect, did know about allow_local_remote_servers).

The page on trying to set up a new access token for Gitlab Integration in Personal Settings is now gone! Vanished!

`TypeError: n is null
    m index.mjs:133
    m index.mjs:126
    Underscore 3
        be
        n
        k
    formatAccountForSelect PersonalSettings.vue:223
    selectedAccount PersonalSettings.vue:201
    VueJS 3
        get
        evaluate
        Na
    Q PersonalSettings.vue:5
    VueJS 18
        _render
        a
        get
        e
        mount
        $mount
        init
        v
        v
        Pr
        _update
        a
        get
        e
        mount
        $mount
        _init
        Ra
    <anonymous> personalSettings.js:22
    <anonymous> personalSettings.js:24
    <anonymous> personalSettings.js:24
[vue.runtime.esm.js:3065:16](webpack:///integration_gitlab/node_modules/vue/dist/vue.runtime.esm.js)
    VueJS 21
        dn
        un
        ln
        _render
        a
        get
        e
        mount
        $mount
        init
        v
        v
        Pr
        _update
        a
        get
        e
        mount
        $mount
        _init
        Ra
    <anonymous> personalSettings.js:22
    <anonymous> personalSettings.js:24
    <anonymous> personalSettings.js:24`
    
  
![fe2f0c41-9adb-48cf-84ce-69b8d4ba962c](https://github.com/user-attachments/assets/9149b4aa-73bd-490c-b815-acd3d0ce7933)

System Info:
NC 29.0.5
Gitlab Integration 3.1.1
TrueNAS 23.04 (can't imagine a world this is the cause)

**Comment by kyteinsky** [comment]
Hello, sorry that you faced this issue. Please make sure to run `delete from oc_gitlab_accounts` before upgrading to the new version.
