### ISSUE TITLE
[Feature Request] Multi gitlab instance

### ISSUE THREAD

**Issue by Maxence1502** [nextcloud/integration_gitlab#14]
Hello !

I have 2 differents gitlab servers (for 2 companies) and I would like to see both with your app.
I can only add one server in the settings. Is it possible to add a 2 one ? Or more ?

**Comment by splitt3r** [comment]
Duplicate of  #10

**Comment by cClaude** [comment]
@Maxence1502 Could you close this issue and move your comment on #10 (or up-vote) to avoid noise ?
