### ISSUE TITLE
OAuth tokens without expiration to be removed

### ISSUE THREAD

**Issue by kc9jud** [nextcloud/integration_gitlab#40]
OAuth tokens without expiration are being removed with GitLab 15.0: https://docs.gitlab.com/ee/update/deprecations#oauth-tokens-without-expiration

Of course, if I try setting up the GitLab integration with an expiring token, it only works for two hours. I'm not sure how this integration should be modified to continue operating...

**Comment by eneiluj** [comment]
Thanks a lot for mentioning this change in GitLab.

Token refresh is now implemented and available in v1.0.4-1-nightly. Could you give it a try?
It would be nice to also check the app is still working fine with personal tokens.

**Comment by eneiluj** [comment]
How did you install the nightly?
The settings location didn't change :grin:.

**Comment by kc9jud** [comment]
Downloaded the tarball from GitHub, expanded it into `custom_apps`, set permissions, ran `occ app:update`...

**Comment by eneiluj** [comment]
I just tried with the same archive on a NC 22 instance and...it works :grin:. Check if there is any error in the browser console logs and NC server logs.

**Comment by kc9jud** [comment]
I'm seeing a 302 redirect from `/custom_apps/integration_gitlab/js/integration_gitlab-adminSettings.js` to `/apps/dashboard/` -- that seems wrong.

**Comment by kc9jud** [comment]
It appears `v1.0.4-1-nightly` fixes this issue -- I can now get notifications from GitLab 15.0.1 through this integration.
