### ISSUE TITLE
https connect error

### ISSUE THREAD

**Issue by wenlong1234** [nextcloud/integration_gitlab#43]
I install gitlab with ssl certificate created by myself。i use gitlab integration has error as follows:
Error getting OAuth access token. cURL error 60: SSL certificate problem: self signed certificate (see https://curl.haxx.se/libcurl/c/libcurl-errors.html) for https://10.100.100.151/oauth/token

how can i solve this problem?

**Comment by MB-Finski** [comment]
Closing this issue as solved as per Julien's reply.
