### ISSUE TITLE
Error in GitlabWidget.php

### ISSUE THREAD

**Issue by airbat** [nextcloud/integration_gitlab#47]
Error in /lib/Dashboard/GitlabWidget.php on line 51.
Dashboard can't be loader because of this mistake 👍 

Bad code : private IConfig $config;
Good code : private $config;

**Comment by HusseinKabbout** [comment]
Same issue here. Had to disable gitlab integration to be able to load the dashboard.

**Comment by eneiluj** [comment]
Thanks for reporting this.

It is actually a syntax which is only supported in PHP >= 7.4
Sorry for the inconvenience.

v1.0.5 is out and should work for you.
Could you try it?

**Comment by airbat** [comment]
Hi, problem solved with last update.
Regards 👍
