### ISSUE TITLE
Repo Search Error

### ISSUE THREAD

**Issue by kernstock** [nextcloud/integration_gitlab#48]
My Nextcloud instance shows an error when using the global search functionality, saying the search for GitLab repos failed.

Here is the according Nextcloud Log entry:

> [no app in context] Fehler: Exception: Argument 3 passed to OCA\Gitlab\Service\GitlabAPIService::searchRepositories() must be of the type int, string given, called in /var/www/nextcloud/apps/integration_gitlab/lib/Search/GitlabSearchReposProvider.php on line 125 in file '/var/www/nextcloud/apps/integration_gitlab/lib/Service/GitlabAPIService.php' line 93 at <<closure>>
> 
> 0. /var/www/nextcloud/lib/private/AppFramework/App.php line 172
>    OC\AppFramework\Http\Dispatcher->dispatch()
> 1. /var/www/nextcloud/lib/private/Route/Router.php line 298
>    OC\AppFramework\App::main()
> 2. /var/www/nextcloud/ocs/v1.php line 62
>    OC\Route\Router->match()
> 3. /var/www/nextcloud/ocs/v2.php line 23
>    require_once("/var/www/nextcloud/ocs/v1.php")
> 
> GET /ocs/v2.php/search/providers/gitlab-search-repos/search?term=nj&from=%2Fsettings%2Fuser%2Fconnected-accounts
> from 141.22.142.200 by paul.kernstock at 2022-08-30T12:48:02+00:00

**Comment by eneiluj** [comment]
Thanks for the issue. Refactoring mistake...

v1.0.6 should be fine.

**Comment by kernstock** [comment]
It is indeed, thanks!
