### ISSUE TITLE
gitlab at non default port

### ISSUE THREAD

**Issue by conloos** [nextcloud/integration_gitlab#50]
Hi everyone,

I'm not able to connect to a gitlab on a non 443 port.
My LAB-Instance is at 8443, e.g.: https://example.com:8443/
Connecting to that Instance shows an error.
Connecting to my gitlab.com account works.

Thanks Frank

**Comment by julien-nc** [comment]
Hi, could you provide more information?
* browser console error
* browser network error
* server log error

A test account on such instance could be of great help to fix this issue.
