### ISSUE TITLE
Mandatory parameter userID missing to generate URL for route

### ISSUE THREAD

**Issue by yuisheaven** [nextcloud/integration_gitlab#55]
The Nextcloud Log:

[no app in context] Fehler: Symfony\Component\Routing\Exception\MissingMandatoryParametersException: Some mandatory parameters are missing ("userId") to generate a URL for route "integration_gitlab.gitlabAPI.getUserAvatar". at <<closure>>

 0. /var/www/vhosts/web302667.roc504.rockinghoster-business.cloud/cloud.tobias-jakob.dev/3rdparty/symfony/routing/Generator/UrlGenerator.php line 160
    Symfony\Component\Routing\Generator\UrlGenerator->doGenerate()
 1. /var/www/vhosts/web302667.roc504.rockinghoster-business.cloud/cloud.tobias-jakob.dev/lib/private/Route/Router.php line 353
    Symfony\Component\Routing\Generator\UrlGenerator->generate()
 2. /var/www/vhosts/web302667.roc504.rockinghoster-business.cloud/cloud.tobias-jakob.dev/lib/private/URLGenerator.php line 103
    OC\Route\Router->generate()
 3. /var/www/vhosts/web302667.roc504.rockinghoster-business.cloud/cloud.tobias-jakob.dev/apps/integration_gitlab/lib/Search/GitlabSearchIssuesProvider.php line 200
    OC\URLGenerator->linkToRoute()
 4. /var/www/vhosts/web302667.roc504.rockinghoster-business.cloud/cloud.tobias-jakob.dev/apps/integration_gitlab/lib/Search/GitlabSearchIssuesProvider.php line 131
    OCA\Gitlab\Search\GitlabSearchIssuesProvider->getThumbnailUrl()
 5. <<closure>>
    OCA\Gitlab\Search\GitlabSearchIssuesProvider->OCA\Gitlab\Search\{closure}("*** sensitive parameters replaced ***")
 6. /var/www/vhosts/web302667.roc504.rockinghoster-business.cloud/cloud.tobias-jakob.dev/apps/integration_gitlab/lib/Search/GitlabSearchIssuesProvider.php line 130
    array_map()
 7. /var/www/vhosts/web302667.roc504.rockinghoster-business.cloud/cloud.tobias-jakob.dev/lib/private/Search/SearchComposer.php line 160
    OCA\Gitlab\Search\GitlabSearchIssuesProvider->search()
 8. /var/www/vhosts/web302667.roc504.rockinghoster-business.cloud/cloud.tobias-jakob.dev/core/Controller/UnifiedSearchController.php line 105
    OC\Search\SearchComposer->search()
 9. /var/www/vhosts/web302667.roc504.rockinghoster-business.cloud/cloud.tobias-jakob.dev/lib/private/AppFramework/Http/Dispatcher.php line 225
    OC\Core\Controller\UnifiedSearchController->search()
10. /var/www/vhosts/web302667.roc504.rockinghoster-business.cloud/cloud.tobias-jakob.dev/lib/private/AppFramework/Http/Dispatcher.php line 133
    OC\AppFramework\Http\Dispatcher->executeController()
11. /var/www/vhosts/web302667.roc504.rockinghoster-business.cloud/cloud.tobias-jakob.dev/lib/private/AppFramework/App.php line 172
    OC\AppFramework\Http\Dispatcher->dispatch()
12. /var/www/vhosts/web302667.roc504.rockinghoster-business.cloud/cloud.tobias-jakob.dev/lib/private/Route/Router.php line 298
    OC\AppFramework\App::main()
13. /var/www/vhosts/web302667.roc504.rockinghoster-business.cloud/cloud.tobias-jakob.dev/ocs/v1.php line 63
    OC\Route\Router->match()
14. /var/www/vhosts/web302667.roc504.rockinghoster-business.cloud/cloud.tobias-jakob.dev/ocs/v2.php line 23
    require_once("/var/www/vhosts ... p")

GET /ocs/v2.php/search/providers/gitlab-search-issues/search?term=issue1&from=%2Fapps%2Fdashboard%2F
from xxxx by xxxx at 2022-12-19T21:05:44+00:00

**Comment by yuisheaven** [comment]
additional information:
This error only shows up if I try to search an issue in Nextcloud search. 
The widget within Nextcloud Dashboard is working.

The connected gitlab instance uses a "read_api" token and itself is a gitlab community edition self hosted behind a reverse proxy

**Comment by julien-nc** [comment]
Hi, thanks for the bug report. This is fixed in v1.0.11 which is out.
Feel free to reopen this issue if needed.
