### ISSUE TITLE
[Feature Request] Allow multiple Instances

### ISSUE THREAD

**Issue by KaeTuuN** [nextcloud/integration_gitlab#69]
At the Moment it is only possible to connect to one Instance per Account. This is not very useful if you have a big company with multiple Instances or a private and a company Instance.

From my point of view, there are some points to discuss:

1. One Dashboard per Instance (if possible), all Instances on one Dashboard or user decision?
2. If all are on one Dashboard, how to differentiate between the Instances?

**Comment by vengefulpunk** [comment]
I agree this could be useful however is this currently a restriction by the nextcloud integration or gitlab?

**Comment by KaeTuuN** [comment]
As far as I know it is a limitation of nexcloud.

**Comment by MB-Finski** [comment]
Duplicate of #10 so we should continue the discussion there. Unfortunately, AFAIK, there's no way to currently dynamically spawn dashboard widgets without implementing a separate php class for each one. The related issue at the server repo was closed as stale, unfortunately: https://github.com/nextcloud/server/issues/24658
